### ISSUE TITLE
Can't scrape NYT puzzle Sunday June 19

### ISSUE THREAD

**Issue by thbeckpr** [jpd236/CrosswordScraper#15]
Received this message:
[Grant permission (needed to scrape grid graphics)](moz-extension://8d2ba050-9fca-478b-836d-3c9e033519ec/popup.html#)

I went to options page, checked the unicode support box and changed the ink saver setting. There is no OK or Save changes button. I closed the window, but still cannot scrape the puzzle.

Is  there a permissions setting somewhere else? Is this the NYT getting cute?

**Comment by jpd236** [comment]
That message should be a link you can click - when clicking it, it should show the permission prompt needed to scrape the puzzle. If you have multiple windows open, the prompt can show up next to a different window (due to a bug in Chrome), so if you don't see the prompt, try making sure you only have one Chrome window open before clicking it. Does that resolve the problem?

(This puzzle has grid art supported in the JPZ format that we need to download which is hosted on a different site, hence the permission prompt.)

**Comment by thbeckpr** [comment]
Yes, thank you.

**Comment by jpd236** [comment]
Great! Closing this out. Will keep this in mind to see if I can come up with a more obvious way of indicating how to resolve the issue.
