### ISSUE TITLE
Chrome bug?

### ISSUE THREAD

**Issue by mmespeer** [jpd236/CrosswordScraper#17]
When I use Crossword Scraper I get the window to make my choice, I choose PUZ and the download box slips behind the Scraper box and I can't click to download. This has happened before. Is there a way to get around it?

**Comment by jpd236** [comment]
Strange - I'm not sure what's happening there. What browser are you using?

Some thoughts off the top of my head would be:

- Try downloading a file from another site, moving the download box, and then trying again (in case it's remembering its last position)
- Turn off the prompt to ask for a destination folder when downloading and just have files automatically download to a folder of choice (then there's no dialog to appear and the file will just download)
- Right click the PUZ link and click "Open link in new tab/window". That will move the popup to a dedicated window/tab and you can then click the download link.

Does one of those help?

**Comment by mmespeer** [comment]
Thanks. I'm using Chrome. I've turned off the prompt to ask for a destination. That should help.
    On Monday, July 25, 2022 at 02:33:39 PM EDT, Jeff Davidson ***@***.***> wrote:  
 
 


Strange - I'm not sure what's happening there. What browser are you using?

Some thoughts off the top of my head would be:
   
   - Try downloading a file from another site, moving the download box, and then trying again (in case it's remembering its last position)
   - Turn off the prompt to ask for a destination folder when downloading and just have files automatically download to a folder of choice (then there's no dialog to appear and the file will just download)
   - Right click the PUZ link and click "Open link in new tab/window". That will move the popup to a dedicated window/tab and you can then click the download link.

Does one of those help?

**Comment by jpd236** [comment]
Got it. It seems like an issue on the Chrome side if the download prompt is showing up underneath a Chrome extension popup which launches it, rather than on top of it. There's not really anything I can think of that we can do on the extension side to influence where the download prompt pops up - all we're doing is creating a file URL and Chrome is responsible for everything that happens when you click it.

I'll have to close this as infeasible; hopefully the workaround is reasonable enough here. Will keep an eye for more reports to see if this becomes a pattern; if so, I guess at most we can try to create a small sample test case and pass the report along to Chrome.
