### ISSUE TITLE
Feature request: click on plug-in icon to download preferred file format

### ISSUE THREAD

**Issue by arelkin** [jpd236/CrosswordScraper#21]
Adding options to preferences to allow clicking on plugin-icon to automatically download users preferred file format. (no option chosen will bring dropdown menu when clicking on icon

![preferred-file-format-radios](https://user-images.githubusercontent.com/213207/198336607-d9975e50-b18f-4a1f-8b0f-00d3c3aad372.gif)

Or

![preferred-file-format](https://user-images.githubusercontent.com/213207/197611265-2914d61f-81f5-461d-b765-76c2d583380d.gif)

**Comment by jpd236** [comment]
I'm supportive of this - saves a click for each download in the common case that you always want the same format and there's exactly one puzzle on the page. I was able to prototype it and it does seem to work.

Some thoughts / things to iron out:

- What should be the behavior of the popup? AFAIK we have to show it, though we can close it automatically. So I think we should show a loading spinner while the scraping is happening, but once done we can automatically start the download and close the window.
- What happens if there's not exactly one puzzle on the page? I think the best thing to do in this case is to show the usual popup. With zero this is obvious; with more than one, I don't think it's 100% clear that the user would intend to download all of the puzzles on the page. (For example, they might have a blog open with older posts). Better to ask to be sure, and there's still value here in automatically downloading in the case that there's exactly one puzzle.
- What happens if there's a conversion error with the selected format? Not too common, but possible, typically due to a bug in the scraper. We should render the usual list (of one element) and show the dialog we'd normally show so the user can try another format or report the issue.
- Should probably provide a fallback option that forces open the menu so you don't have to turn off the setting in case you want to download something different. I think it is possible to show another option in the right-click menu which should work here.
- Need to see how Firefox behaves (only tested in Chrome).

**Comment by arelkin** [comment]
Yes, these are valid concerns. Is there a way for Scraper users to begin testing your proof of concept to find out how these issue might be tested and tweaked into place?

**Comment by jpd236** [comment]
I've checked in an initial cut of this. Most of the above concerns are addressed; the main risks are:

- If you close the window too quickly on Firefox, the download fails to start. I couldn't find a proper way of dealing with this short of waiting an arbitrary amount of time (100ms) before closing the window; this works well for me, but could obviously fail in other scenarios without something more formal to tie it to. Not sure if there's a better way, but not feeling particularly inclined to investigate too much more deeply as Chrome is working fine.
- I couldn't find a way to make a fallback option work (right click menu option to force the window open). Hopefully not a big deal in practice since the window will show up if the download can't be done.

If you want to test this before the next release, you can try one of the attached snapshots depending on your browser. Instructions for testing a custom release are here: https://github.com/jpd236/CrosswordScraper/wiki/Troubleshooting#installing-a-custom-release-in-chrome

[CrosswordScraper-productionChrome-1.2.16-SNAPSHOT.zip](https://github.com/jpd236/CrosswordScraper/files/9944835/CrosswordScraper-productionChrome-1.2.16-SNAPSHOT.zip)
[CrosswordScraper-productionFirefox-1.2.16-SNAPSHOT.zip](https://github.com/jpd236/CrosswordScraper/files/9944836/CrosswordScraper-productionFirefox-1.2.16-SNAPSHOT.zip)

**Comment by arelkin** [comment]
Have run a few tests. So far, so good. Will continue testing.
But so far, looks great. Thanks for implementing this suggestion.

**Comment by arelkin** [comment]
Firefox must continually check to see if all plugins are officially installed. I took your zip and renamed it to the hex plugin name in my FF profile {d481.....d74d}, then changed the extension to .xpi.

This worked fine for a while, till FF "checked" its plugins. Since now CS wasn't officially authorized, it deactivated it. :-(

I had to go back to the official version. But, I did get to test it out. Looks great and works great.

**Comment by jpd236** [comment]
Glad to hear it's working.

I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1799340 in the hopes that I can get to the bottom of why the arbitrary 100ms delay is necessary for Firefox, but will probably just release this either way in the next few weeks.

**Comment by arelkin** [comment]
Excited for the actual release. 

As mentioned, I was only able to use it until FF did its authorized-install check, after which, it turned off the plug-in with no way to reactivate.

**Comment by arelkin** [comment]
I found this information on how to temporarily install a pre-release version of a plug-in, without FF continually disabling the plug-in as a not legitimate install.

https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/

**Comment by jpd236** [comment]
Thanks - updated https://github.com/jpd236/CrosswordScraper/wiki/Troubleshooting to include these instructions for Firefox.

I uploaded the new version (1.2.16) a couple of days ago and it's available on Firefox, so closing this out. For whatever reason, the Chrome update is taking a bit longer to approve, but it should hopefully go live soon there as well.
