### ISSUE TITLE
Italics overprints

### ISSUE THREAD

**Issue by haberarts** [jpd236/CrosswordScraper#34]
I use crossword scraper for puzzles in The New Yorker, opening them in pdf. It's been terrific ever since I added it to the browser months ago. But one flaw: when a clue or the puzzle's title contains italics, the italic letters print over the nearest roman letters, obscuring them both. Here is the latest puzzle in which this occurs: 

https://www.newyorker.com/puzzles-and-games-dept/cryptic-crossword/2023/08/13

**Comment by jpd236** [comment]
Thanks for the report! This looks like a regression due to some recent changes in PDF rendering.

https://github.com/jpd236/kotwords/commit/b40f39d8ad4105d354a3ce349e38d9257240fd84 should resolve this, and I'll build and upload a new version of the extension (1.3.5) shortly, though it may take a few days to be approved.

**Comment by haberarts** [comment]
I'm impressed at how quickly you were able to address this. Thanks! Looking forward to the upgrade; I can report back then on whether it worked for me.
