### ISSUE TITLE
Amuse Labs: Scrape Error across multiple domains

### ISSUE THREAD

**Issue by arelkin** [jpd236/CrosswordScraper#36]
As mentioned in the error note, "Amuse Labs has begun introducing obfuscation measures...."

Saw the error here:
https://www.briangubin.com/post/themed-132-lets-out-some-gas
https://matthewluter.com/puzzle-117/
https://puzzlesthatneedahome.blogspot.com/2023/08/puzzle-122-themeless-88-da-bomb-puzzle.html

But not here:
https://www.newyorker.com/puzzles-and-games-dept/crossword/2023/09/05

**Comment by randrzejh** [comment]
https://yourpuzzlesource.com/daily-crossword/
https://fordhamobserver.com/74016/fun-and-games/tuesday-september-5/

as well.

**Comment by jpd236** [comment]
Thanks all. This should be fixed in 1.3.6, once approved by Chrome/Firefox.

In general, PuzzleMe handling is a brittle as they are the only supported provider who actively apply obfuscation to their applet code. As the error page notes, I can't guarantee support forever here. But in this particular case, the changes on their side were minor/cosmetic and simple enough to handle.
