### ISSUE TITLE
Scrape error

### ISSUE THREAD

**Issue by qvart1** [jpd236/CrosswordScraper#37]
It says "scrape error" on the Wall Street Journal site

**Comment by jpd236** [comment]
Thanks for the heads up. This will be fixed in version 1.3.7, which has been submitted to Chrome/Firefox for approval.

In the mean time, if you want a .puz file for this WSJ puzzle (since it only appears to impact tomorrow's puzzle as of this moment), an alternate source is https://www.fleetingimage.com/wij/xyzzy/23-wsj.html.

**Comment by qvart1** [comment]
I just saw this message because it went to the Trash folder instead of my
inbox. Thanks for the fix and reply 👍 - Geoff
