### ISSUE TITLE
PDF crashing my printer

### ISSUE THREAD

**Issue by arelkin** [jpd236/CrosswordScraper#7]
Browser: Firefox/Macintosh
Scraper Plugin: 1.2.4
Printer: HP LaserJet 5MP

With this HP, two lights start blinking as it processes the file before printing. What happens with a CrosswordScraper PDF is the two light start blinking, then ALL the lights light up and the printer stops.

I've had this printer for twenty five years (yes, I know -- old). But it's a reliable workhorse, that still works.

In all the years I've had this printer, this is the first time anything like this has happened.

Attached is an example PDF created from this xword:
https://webflow-production.spyscape.com/crosswords/puzzle-158-two-in-one

[LorraineGoodmanEditedByWillNediger-TwoInOne.pdf](https://github.com/jpd236/CrosswordScraper/files/7922736/LorraineGoodmanEditedByWillNediger-TwoInOne.pdf)

**Comment by jpd236** [comment]
That's quite an issue!

Unfortunately, I don't really think it's feasible for me to do anything about this. The extension just uses the jsPDF library (https://github.com/parallax/jsPDF) to draw a bunch of text, and shapes to a PDF page - I don't know the first thing about the PDF format otherwise. As far as I know, the PDFs work fine with other printers. If you're able to find out more details about what exactly in the PDF causes this behavior, maybe there'd be some sort of workaround, but otherwise I unfortunately can't take any action here.

As a workaround, you could try opening the JPZ files in another solver like https://crosswordnexus.com/solve and printing them there. (Though this particular site also uses jsPDF, so you may run into the same problem...)
